steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/devops-316215/github.com/premiram/devops-project:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/devops-316215/github.com/premiram/devops-project:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'devops-316215', '--region=asia-southeast1', '--platform=managed', '--image=gcr.io/devops-316215/github.com/premiram/devops-project:$SHORT_SHA']

