steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/devopsproject-316402/devopsproject-316402/github.com/premiram/devodevops-project:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/devopsproject-316402/devopsproject-316402/github.com/premiram/devodevops-project:$SHORT_SHA']
